/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;
import java.util.Random;

public class Library {
  public static int[] roll(int n) {
    //create the resulting array
    int[] result = new int[n];

    //get random nums
    Random rand = new Random();

    //populate the array
    for (int i = 0; i < n; i++) {
      result[i] = rand.nextInt(6) + 1;
    }

    //return the array
    return result;
  }

  public static boolean ContainsDuplicates(int[] arr) {
    //create result
    //boolean result = false;

  /*  //itterate through the list
    for (int num: arr) {
      //check if it's in the array already
      int count = 0;
      for (int innerNum: arr) {
        if (num == innerNum){
          //if it's in there increment the count
          count++;
          if (count > 1){
            //if it appears more than once return false
            result = true;
          }
        }
      }
    }
    //return the result
    return result;*/

    //itterate through the list
    for (int i = 0; i < arr.length; i++) {
      //check if it's in the array already
      for (int j = i+1; j < arr.length; j++) {
        //if it's in there return false
        if (arr[i] == arr[j]){ return true;}
        }
      }
    return false;
  }

  private static float sum(float[] arr) {
    float result = 0;
    for (float num : arr) {
      result += num;
    }
    return result;
  }

  public static float average(float[] arr) {
    return sum(arr) / arr.length;
  }

  public static float arrayAverage(float[][] arr) {
    //create and populate new array of sums
    float[] toAverage = new float[arr.length];
    for (int i = 0; i < arr.length; i++) {
      toAverage[i] = average(arr[i]);
    }
    System.out.println(Arrays.toString(toAverage));

    return average(toAverage);
  }
}
