/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    readFile("src/test/resources/gates.js");
  }

  public static String readFile(String filePath) {
    //open and read the scanner
    File openFile = new File(filePath);

    //begin scanning the file
    Scanner scanningFile;
    try {
      scanningFile = new Scanner(openFile);
    } catch (FileNotFoundException exception) {
      System.out.println(exception);
      return "Failed to locate file";
    }
    //iterate through the line and add no list of bad ones as needed
    StringBuilder result = new StringBuilder();
    int currentLine = 0;
    while (scanningFile.hasNext()) {
      //increment line number
      String line = scanningFile.nextLine();
      currentLine++;
      //continue in line is empty
      if (line.isEmpty()) continue;
      //continue if line ends with an {, } or ;
      if (line.endsWith("{") || line.endsWith("}") || line.endsWith(";")) continue;
      //continue if line contains if or else
      if (line.contains("if") || line.contains("else")) continue;
      //if none of the above are true add line to return statement and print.
      String lintingError = "Line " + currentLine + ": Missing semicolon.";
      System.out.println(lintingError);
      result.append(lintingError).append("\n");
    }
    //return the resulting errors
    return result.toString();
  }
}
